version: '3.3'
services:
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - web_network
  certbot:
    image: certbot/certbot:latest
    volumes:
   #   - ./nginx/www://certbot/:rw
   # first host than container
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    #ports:
    #  - 80:80
    networks:
      - web_network
networks:
  web_network:
    driver: bridge
